### ISSUE TITLE
Color handling in single_panel is broken

### ISSUE THREAD

**Issue by sdeastham** [geoschem/gcpy#143]
https://github.com/geoschem/gcpy/blob/b113e3cbcaff605bb654aaa22be9762d0a597a42/gcpy/plot.py#L3006

When calling `single_panel` with cubed-sphere data, only one panel is returned (since `plot` is assigned in a loop). This is a problem if you want to adjust the color limits. Trying to adjust the color limits manually is also problematic; providing `vmin` and `vmax` to `single_panel` results in an error thrown (because `norm` cannot also be supplied, but is supplied by default in the call to `pcolormesh`). On the other hand, if you define `norm` explicitly (e.g. with a call to `maplotlib.colors.Normalize`) and do not define `vmin` or `vmax`, another error is thrown on line 3040 (https://github.com/geoschem/gcpy/blob/b113e3cbcaff605bb654aaa22be9762d0a597a42/gcpy/plot.py#L3040) because `vmin` and `vmax` are not present. Issue identified by @sadiatoma during meeting. Suggest two possible and complementary solutions:

1. Add each result from `pcolormesh` to a list and return that (see e.g. https://github.com/sdeastham/gcgridobj/blob/2cd78b8bc7f7d58f698467b60e5c5ae53b2050eb/gcgridobj/plottools.py#L319); and
2. Revamp handling of `norm`, `vmin`, and `vmax` to avoid assumptions about their presence/absence.

**Comment by laestrada** [comment]
Thanks for posting Seb -- We will try to fix this. In the meantime users can regrid to lat/lon using [sparselt](https://github.com/LiamBindle/sparselt).

**Comment by laestrada** [comment]
@sdeastham It turns out that matplotlib version >3.4 no longer supports simultaneously supplying the `vmin`/`vmax` parameters and `norm`. `vmin/vmax` must instead be applied inside the normalization. This issue applies to lat/lon and cubedsphere grids. 

I have pushed a fix to the `dev` branch (see  c8d820b). Closing this issue out unless there are other concerns.

**Comment by sdeastham** [comment]
Thanks @laestrada ! I have two remaining issues (one major, one trivial):

Major issue: the routine still does not return the handles for all the `pcolormesh` images when using CS data. This makes working with the plot rather painful (e.g. if you want to change color limits after plotting). Could we e.g. return a list of all 6 images, not just the last plotted one?

Trivial issue: pedantically I'd recommend changing `== None` to `is None` (based on PEP 8), but I think the cases where that causes problems are pretty niche.

**Comment by laestrada** [comment]
Ah, I see the issue now! @sdeastham I have taken your suggestions and the bug fix is in PR #149. If this looks good to you I will merge and close this issue.

**Comment by sdeastham** [comment]
Looks great! As long as any other routines designed to accept output from the routine are ready for it, I think we're good to go.

**Comment by laestrada** [comment]
Note that to preserve existing functionality within other gcpy scripts I have added `return_list_of_plots` as a boolean parameter for `single_panel` with the default set to `False`. To retrieve a list format of the generated plots, set this parameter to `True`.
