### ISSUE TITLE
[BUG/ISSUE] Packages not found when creating env with latest conda version

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#202]
## Describe the bug
I am creating a new python environment using conda 22.11.1 and GCPy 1.3.2. I am following instructions [here](https://gcpy.readthedocs.io/en/latest/Getting-Started-with-GCPy.html). FYI I just overhauled that page so I may be the first person to do the install with this particular sequence of commands.

I am now getting an error when creating the environment:
```
(base) GCPy % conda env create -n gcpy_env --file=environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - esmpy==8.1.1
  - esmf==8.1.1
```

I searched for available packages of `esmf` and `esmpy` and found that only 8.4.0 is available.  I am using the following commands to search:
```
conda search esmpy --channel conda-forge
conda search esmf --channel conda-forge
```

I tried changing the `esmf` and `esmpy` versions to 8.4.0 in `environment.yml` and then creating an environment from that. This results is many package conflicts.

## To Reproduce
Follow the instructions on the GCPy install ReadTheDocs page linked to above. Try to create an environment using either the `dev` or `main` branches of GCPy.

## Expected behavior
There should be no problems creating a python environment from `environment.yml` using conda.

**Comment by yantosca** [comment]
Hi @lizziel: I use the Miniconda version 4.12 or 4.13.  That might pull the older ESMF version.

**Comment by kilicomu** [comment]
@lizziel +1 to this. I tried removing version specifications and using an environment file as below:
```
name: gcpy
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cartopy
  - esmpy
  - geoschem-gcpy
  - ipython
  - joblib
  - matplotlib
  - numpy
  - pandas
  - pypdf2
  - scipy
  - sparselt >= 0.1.3
  - xarray
  - xbpch
  - xesmf
```

The environment solved and installed, but importing GCPy doesn't work due to a broken `import ESMF` (the module name has changed to `esmpy` since 8.1.x).

**Comment by yantosca** [comment]
This should now be resolved with GCPy 1.3.3: https://github.com/geoschem/gcpy/releases/tag/1.3.3

We now require installation of GCPy with Conda 4.12.0, which will avoid the package conflicts described in this issue.

**Comment by lizziel** [comment]
If anyone runs into this issue see the ReadTheDocs updated instructions for [installing conda 4.12.0](https://gcpy.readthedocs.io/en/stable/Getting-Started-with-GCPy.html#steps-to-install-conda-4-12-0-with-miniconda) from @yantosca.

Let's keep this issue open to remind ourselves to keep looking into getting GCPy to work with the newer conda.

**Comment by kilicomu** [comment]
Hey guys - are we sure that downgrading to `miniconda` 4.12.0 resolves this issue? I wiped out my newer `miniconda` from my system to test this, ran through the instructions on the `gcpy` documentation, and still get this:

```
(base) klcm500@UOY23M031 GCPy % conda --version
conda 4.12.0
(base) klcm500@UOY23M031 GCPy % conda env create -f environment.yml 
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - esmpy==8.1.1
  - esmf==8.1.1

```

**Comment by yantosca** [comment]
@kilicomu: I have since created the gcpy environment on a few different platforms without running into this issue.  But I haven't tried in the last week or so.  I know, it is a pain that ESMF removed the older versions.

**Comment by lizziel** [comment]
I am creating a gcpy environment on a new cluster and had no issues getting ESMF 8.1.1 using conda 4.12.0. Do you see anything weird if you do `conda config --show`?

**Comment by kilicomu** [comment]
I have a suspicion that it was still using some remnants of the newer conda version that I had installed (I wiped it to try this).

I'll have a go on a different system.

**Comment by lizziel** [comment]
@kilicomu, can this issue be closed now?

**Comment by kilicomu** [comment]
@lizziel Sure close it for now - I haven't had any time to check again. I'll reopen if necessary.
